version: 0.2

phases:
    build:
        commands:
            - echo 'Building Services App............'
            - mvn clean package
        
artifacts:
    files: '**/*'
    base-directory: target/CST-323-Blog-Website-AWS
    
cache:
  paths:
    - '/root/.m2/**/*'
